# Generated by Django 3.2.9 on 2021-11-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('points', models.IntegerField(verbose_name='Amount of points per donation')),
                ('amount', models.IntegerField(verbose_name='Amount of donation')),
                ('post_code', models.CharField(blank=True, max_length=7)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
