# Generated by Django 3.2.9 on 2021-11-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='/static/empty.png', upload_to='offers/%Y/%m/%d/'),
        ),
    ]
