# Generated by Django 3.2.9 on 2021-11-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='tags',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='/static/empty_offer.png', upload_to='offers/%Y/%m/%d/'),
        ),
    ]
