# Generated by Django 3.2.9 on 2021-11-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20211113_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='/static/empty_offer.png', upload_to='static/uploads/offers/%Y/%m/%d/'),
        ),
    ]
