# Generated by Django 3.2.9 on 2021-11-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='location',
            field=models.CharField(default='32°40’34.19″N 117° 9’27.58″W', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='/static/empty_offer.png', upload_to='media/uploads/offers/%Y/%m/%d/'),
        ),
    ]
