# Generated by Django 3.2.9 on 2021-11-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_appuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_code',
            field=models.TextField(blank=True, max_length=7),
        ),
    ]
