# Generated by Django 3.2.9 on 2021-11-13 17:24

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post_code',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
