# Generated by Django 3.2.9 on 2021-11-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211113_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/static/empty_user.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
