# Generated by Django 3.2.9 on 2021-11-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/static/empty_user.png', upload_to='media/uploads/users/%Y/%m/%d/'),
        ),
    ]
